spring:
datasource:
url: jdbc:postgresql://localhost:25432/app
username: app
password: app
jpa:
hibernate:
ddl-auto: validate
properties:
hibernate:
format_sql: true
open-in-view: false
flyway:
enabled: true
locations: classpath:db/migration
server:
port: 8080


app:
jwt:
secret: "change-me-please-32chars-min"
issuer: "resource-booker"
