spring:
  datasource:
    url: jdbc:postgresql://localhost:25431/postgres
    username: app
    password: app
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
  open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: "0123456789ABCDEF0123456789ABCDEF"
    issuer: "resource-booker"
