spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/app
    username: app
    password: app
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
  open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: "change-me-please-32chars-min"
    issuer: "resource-booker"
